name: CI Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --include=dev

      - name: Debug environment
        run: |
          ls -l node_modules/.bin
          npm list --depth=0

      - name: Run tests
        run: |
          chmod +x node_modules/.bin/jest
          npm test
